//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RPS.Library;
using UnityEngine;
using SimpleJSON;
using System.Collections;
using System.Collections.Generic;

namespace RPS.Models
{
	public class HTTPDataProvider
	{
		public const string API_URL = "";
		private WWW webConnection;
		private string url;

		public HTTPDataProvider (string url) : this(url, null)
		{

		}

		public HTTPDataProvider(string url, Dictionary <string, string> formFields) {

			this.url = url;
			if (formFields != null) {
				WWWForm postData = new WWWForm();
				foreach (KeyValuePair<string, string> entry in formFields) {
					postData.AddField(entry.Key, entry.Value);
				}
				this.webConnection = new WWW (this.url, postData);
			} else {
				this.webConnection = new WWW (this.url);
			}
		}

		public bool IsDone() {	
			return this.webConnection.isDone;
		}

		public string GetData() {
			if (this.IsDone ()) {
				return this.webConnection.text;
			}
			return null;
		}

		public JSONNode GetJSONData() {
			if (this.IsDone ()) {
				return JSON.Parse(this.webConnection.text);
			}
			return null;
		}

		public static HTTPDataProvider PostJSONData(string url, string fieldName, JSONNode json) {
			HTTPDataProvider provider;
			Dictionary<string, string> formFields = new Dictionary<string, string> ();
			formFields.Add (fieldName, json.ToString ());

			provider = new HTTPDataProvider (url, formFields);
			return provider;
		}

		public static string FindUrl(Model model) {
			RPS.Library.ApiUrlBuilder builder = new RPS.Library.ApiUrlBuilder (model);
			Debug.Log (builder.Uri.ToString());
			return builder.Uri.ToString();
		}
	}
}




