//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace RPS.Models
{
		public class ModelNotFoundException : Exception
		{
			public ModelNotFoundException (Model model) : base( model.GetType().ToString() + ": No data exists on the server")
			{
			}
		}
}

