//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace RPS.Models
{
	public class User : Model
	{

		private int id;
		private string username;
		private string firstname;
		private string lastname;
		private string emailAddress;
		private string password;
		private int numberOfWins;
		private DateTime created;
		private bool activated;
		private int status;

		public int Id {
			get {
				return this.id;
			}
			set {
				this.id = value;
			}
		}

		public string Username {
			get {
				return this.username;
			}
			set {
				this.username = value;
			}
		}

		public string Firstname {
			get {
				return this.firstname;
			}
			set {
				this.firstname = value;
			}
		}

		public string Lastname {
			get {
				return this.lastname;
			}
			set {
				this.lastname = value;
			}
		}

		public string EmailAddress {
			get {
				return this.emailAddress;
			}
			set {
				this.emailAddress = value;
			}
		}

		public string Password {
			get {
				return this.password;
			}
		}

		public int NumberOfWins {
			get {
				return this.numberOfWins;
			}
			set {
				this.numberOfWins = value;
			}
		}

		public DateTime Created {
			get {
				return this.created;
			}
			set {
				this.created = value;
			}
		}

		public bool Activated {
			get {
				return this.activated;
			}
			set {
				this.activated = value;
			}
		}

		public int Status {
			get {
				return this.status;
			}
			set {
				this.status = value;
			}
		}

		public static User GetByEmailAddress(string emailAddress) {
			return null;
		}

		public static User GetById (int id)
		{
			User user = new User ();
			user.AddApiPathFragment (id);
			user.FetchHTTPData ();
			return user;
		}

		public override bool Update ()
		{
			if (this.NumberOfWins > 0) {
				
				SimpleJSON.JSONNode tournamentJSON = SimpleJSON.JSON.Build();
				tournamentJSON["no_of_wins"].AsInt = this.NumberOfWins;
				this.AddApiPathFragment(this.Id);
				this.PostHTTPData(Tournament.HTTP_FORM_KEY_UPDATE, tournamentJSON);
				return true;
			}
			return false;
		}

		public override bool Insert ()
		{
			return false;
		}		

		public override void ConvertToModel ()
		{
			this.Id = (int)this.GetValue ("id", TypeCode.Int32);
			this.Username = this.GetValue ("username");
			this.Firstname = this.GetValue ("firstname");
			this.Lastname = this.GetValue ("lastname");
			this.EmailAddress = this.GetValue ("email_address");
			this.password = this.GetValue ("password");
			this.NumberOfWins = (int)this.GetValue ("no_of_wins", TypeCode.Int32);
			this.Created = (DateTime)this.GetValue("created", TypeCode.DateTime);
			this.Activated = (bool)this.GetValue ("activated", TypeCode.Boolean);
			this.Status = (int)this.GetValue ("status", TypeCode.Int32);


		}

		public override string getApiPath() {
			string path = "users";
			if (this.apiPathFragments != null) {
				foreach (string fragment in this.apiPathFragments) {
					path += "/"+fragment;
				}
			}
			return path;
		}

		public override string ToString ()
		{
			return string.Format ("[User: username={0}, firstname={1}, lastname={2}, emailAddress={3}, numberOfWins={4}, created={5}, activated={6}, status={7}]", username, firstname, lastname, emailAddress, numberOfWins, created, activated, status);
		}
		
	}
}

